### ISSUE TITLE
Intervisibility "False" result by the plugin, but "True" in real world

### ISSUE THREAD

**Issue by pyarchinit** [zoran-cuckovic/QGIS-visibility-analysis#10]
Hi,
I'm testing your wonderful plugin.

I've encountered a strange problem.

I have 2 points that have intervisibility in real world, but, your plugin mark them "false" in intervisibility field.

Points are stored into 2 different shapefile
Both have a elevation filed.

The observer point is at 450 meters
Target is at 622 meters

Between them there is a little hill tall 380 meters...is the highest point between observer and target.

I've realized along the intervisibility line a section with profile plugin...the field of view is free as you can see....

[Profile along intervisibility line](http://www.adartesnc.com/FTP/bugscreenshots.PNG)

I think is a tuning problem of my dataset.

What do you think about it? 

Thanks a lot!!! Do you want my dataset to make some test?

Regards
Luca

**Comment by zoran-cuckovic** [comment]
Thanks for signalling this issue - it seems important!
Could you, please, send me the dataset you use (with viewpoints) so that I might reproduce the error?

**Comment by pyarchinit** [comment]
Here a little dataset with the only 2 points envolved:
https://www.dropbox.com/sh/j9942tmmskje1uj/AABfe6axU7uvU5ifur_KrQb7a?dl=0

The epsg id is 25832 for any layer.
The project is set with OTF off

There are 2 field, double and integer, with elevation value.

I set the plugin in this way:
For observer and target I choosed the same layer point_for_test.shp
For elevation I choosed the same field: quota ora dem20_merged (here I've putted the value from dem by sampling tools plugin)

The search radius is set on 15000 (The two points are distant 11 Km)

I choosed a cumulative for raster output.

Let me knows if I was wrong something.

Thank a lot and regards.
Luca

**Comment by zoran-cuckovic** [comment]
Hello,

I've looked into your data: you have irregular sized pixels (20.9565 by 31.8014). That issue was already signalled [here](https://github.com/zoran-cuckovic/QGIS-visibility-analysis/issues/4). I will put some kind of a test to catch this type of error. (you can expect a lot of problems with such a dataset...)

Regards!

**Comment by pyarchinit** [comment]
Oh! Wonderfull! I'll recreate my dem from curvelines, then I'll make another test.

Thanks a lot!!!
Luca
