### ISSUE TITLE
Problem with QGIS 2.18.15

### ISSUE THREAD

**Issue by johnberkeley** [zoran-cuckovic/QGIS-visibility-analysis#13]
Zoran,
I've really appreciated this excellent plugin, but recently with the latest QGIS build it refuses to open for me. The icon is visible on the toolbar but it doesn't do anything. Can I open it from the folder? ( I am not knowledgeable with Python.)

Appreciate any thoughts you may have.

John

**Comment by zoran-cuckovic** [comment]
Hello!
I work with 2.18.4 - which build are you referring to?

**Comment by johnberkeley** [comment]
I may have figured this out:  when I use QuickMap Services to download various basemaps, your plugin won’t open, at least for me.  If I uninstall the plugin that seems to fix it.

Sometimes, just removing the basemap will fix the problem also.

John Bernstein
Senior Project Manager
The Trust for Public Land
415-800-5281
www.tpl.org<http://www.tpl.org/>

[TPL Vertical NEW logotype]
