### ISSUE TITLE
Python Memory Error - QGIS 2.18.15

### ISSUE THREAD

**Issue by glaw2222** [zoran-cuckovic/QGIS-visibility-analysis#14]
Hello, I'm seeing the following error when generating the view-shed,

An error has occurred while executing Python code: 

MemoryError 
Traceback (most recent call last):
  File "C:/Users/TestStation/.qgis2/python/plugins\ViewshedAnalysis\viewshedanalysis.py", line 197, in run
    Algo)
  File "C:/Users/TestStation/.qgis2/python/plugins\ViewshedAnalysis\doViewshed.py", line 409, in Viewshed
    mx_vis = numpy.zeros((full_window_size, full_window_size))
MemoryError

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.16 Las Palmas, d473c3071a 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/TestStation/.qgis2/python
C:/Users/TestStation/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/TestStation/.qgis2//python
C:/Users/TestStation/Desktop/GIS/GIS

**Comment by zoran-cuckovic** [comment]
Hello!
Check the same issue that was previously raised: https://github.com/zoran-cuckovic/QGIS-visibility-analysis/issues/12
Does that solve the problem ?
