### ISSUE TITLE
Incorrect output for viewshed with 2 points

### ISSUE THREAD

**Issue by Mechintosh** [zoran-cuckovic/QGIS-visibility-analysis#22]
Using QGIS 3 and Visibility Analysis v 0.6.3 I get an issue when I have two points in the same layer.

I create a viewpoint layer containing both of the points and run the viewshed analysis on that layer. The output I get is a layer with 2 colors, max value of 0 and a large square way south of my two points that is black. 

Using the same method but starting with a single point in the original layer works perfectly. 

I work in EPSG:3006 (SWEREF 99 TM)

**Comment by zoran-cuckovic** [comment]
Hello!
Is your file formatted as Single-point or Multi-point (or Multi-part)? Only the Single point/Single part format will work ...
