### ISSUE TITLE
Unable to use QGIS Viewshed plugin

### ISSUE THREAD

**Issue by SonnySaluki** [zoran-cuckovic/QGIS-visibility-analysis#25]
Hi

First I cannot find the icon on my toolbars, it no longer appears
Second when I open the viewshed tool from the processing toolbox I have no observer height and radius parameter input boxes, so unsurprisingly I get the following message
I am use Windows 10 and QGIS 3.4.1 Madeira

![image](https://user-images.githubusercontent.com/46525147/50897662-b45e1480-1404-11e9-98cd-2445fc466660.png)

I should also say that both the points and the raster are in a PostgreSQL database

Thanks in advance

****** 
ERROR! 
Missing fields: 
observ_hgt
radius
Traceback (most recent call last):
File "C:/Users/XXXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ViewshedAnalysis\algorithms\viewshed_raster.py", line 181, in processAlgorithm
raise QgsProcessingException(err)
_core.QgsProcessingException: 
****** 
ERROR! 
Missing fields: 
observ_hgt
radius

Execution failed after 0.64 seconds

Loading resulting layers
Algorithm 'Viewshed' finished

**Comment by zoran-cuckovic** [comment]
Hi!
Please check the tutorial on [https://landscapearchaeology.org/2018/visibility-analysis-0-6/](https://landscapearchaeology.org/2018/visibility-analysis-0-6/). Observer height and other parameters are set in the Create viewpoints module.
