### ISSUE TITLE
QGIS 2.18.16: memory issue with high-altitude observers

### ISSUE THREAD

**Issue by intelligeo** [zoran-cuckovic/QGIS-visibility-analysis#26]
Hi,
I tried to calculate some cumulative binary viewshed from observers like geostationary satellites at equator with a metric-projected dem.tif and I've the following message in the console:

2019-02-06T18:01:27	1	Traceback (most recent call last):
File "C:/Users/me/.qgis2/python/plugins\ViewshedAnalysis\viewshedanalysis.py", line 197, in run Algo)
File "C:/Users/me/.qgis2/python/plugins\ViewshedAnalysis\doViewshed.py", line 409, in Viewshed
mx_vis = numpy.zeros((full_window_size, full_window_size))
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

Can someone provide some help? Is there any type limitation to be considered?
Thank you in advance for your answer.
Kindly, Michael

**Comment by zoran-cuckovic** [comment]
Hello,
Viewshed form a satelite? It is quite probable that your dem is too large to be handled by the plugin, if you take into account the entire globe !  (Calculations are mode on numpy arrays, which are limited in size by available live memory).
Best!
