### ISSUE TITLE
Problem with metric system and pixel shape

### ISSUE THREAD

**Issue by zenekites** [zoran-cuckovic/QGIS-visibility-analysis#27]
I am trying to run  visibility plugin on Qgis 3.4.4.  But unfortunately it fails during the creation of viewpoints with the following error:

ERROR! 
Raster data has to be projected in a metric system!
Traceback (most recent call last):
File "C:/Users/serdarr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ViewshedAnalysis\algorithms\viewshed_points.py", line 187, in processAlgorithm
raise QgsProcessingException(err)
_core.QgsProcessingException: 

and when I project the raster into a metric system I get the following error :
****** 
ERROR! 
Raster pixels are irregular in shape (probably due to incorrect projection)!
Traceback (most recent call last):
File "C:/Users/serdarr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ViewshedAnalysis\algorithms\viewshed_points.py", line 194, in processAlgorithm
raise QgsProcessingException(err)
_core.QgsProcessingException: 
****** 

Would you please help me sort out the problem, since I would love to use this great plugin.

Thanks in advance

**Comment by zoran-cuckovic** [comment]
Hello,
You should give me some more information: which projection are you using (I assume that your data is in Lat/Lon) ?

**Comment by zenekites** [comment]
Hello,

Thanks for your help.

The DEM I use is Aster DEM , which is EPSG:4326. It does not work for
creating viewpoints (requires a metric projection). When I  change the
projection to EPSG:32635  in QGIS, it  does not work due to irregular shape
of pixels. But when I reprojected the raster with Arcmap, it worked. And it
also worked  when I used "*gdal:warpreproject*".

Best Regards



Zoran Čučković <notifications@github.com>, 18 Şub 2019 Pzt, 14:23 tarihinde
şunu yazdı:

**Comment by zoran-cuckovic** [comment]
Hello,
Aster GDEM is a standard DEM dataset; normally there should be no problems. Here is a viewshed model for your UTM projection (zone of Antalya) : 
![image](https://user-images.githubusercontent.com/6622934/52970732-3c94e980-33b5-11e9-9a51-6a41f6c6c81a.png)
I suppose that your problem is related to incorrect projection.

**Comment by zenekites** [comment]
Thank you so much For your help. I will check again.


Zoran Čučković <notifications@github.com>, 18 Şub 2019 Pzt, 21:46 tarihinde
şunu yazdı:
