### ISSUE TITLE
Error: No viewpoints in the chosen area!

### ISSUE THREAD

**Issue by jfaber94** [zoran-cuckovic/QGIS-visibility-analysis#30]
I'm running the latest experimental version of the visibility analysis plugin on QGIS version 3.6 (the most recent stable version will not install on this device or another running an earlier version of QGIS). I've used the create viewpoints tool to indicate the radius and observer height associated with the viewpoints, and when I attempt the viewshed analysis I get an error that reads "No viewpoints in the chosen area!"

I tried using lat/long formatting and projected coordinates, and both give the same result. Any idea what could be causing this issue?

**Comment by zoran-cuckovic** [comment]
Hello, 
This has to be an issue with coordinate systems/projections. I should know more in order to help you with this one ... (did you try to switch off the automatic reprojection to test whether the data aligns properly?)
