### ISSUE TITLE
Vishewed problem

### ISSUE THREAD

**Issue by Jhonnylerony** [zoran-cuckovic/QGIS-visibility-analysis#42]
Hello, I use QGIS 3.1.12 Desktop and EPSG:32717, this is probably relapsing into a very common problem, but I have been checking that I use UTM coordinates so that it is not the typical error. When I create view points there is no problem, the problem is when I use the viewshed application:

>
{ 'ANALYSIS_TYPE' : 0, 'DEM' : 'C:/Users/XXXX/Documents/Peru/Gis/DEM_Perú/DEM_PERÚ.tif', 'OBSERVER_POINTS' : 'Point?crs=EPSG:32717&field=ID:string(255,0)&field=observ_hgt:double(10,4)&field=radius:double(10,2)&uid={c7db06a7-becf-49f2-845b-c91e61c3398e}', 'OPERATOR' : 0, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'REFRACTION' : 0.13, 'USE_CURVATURE' : False }

******* 
ERROR! 
No viewpoints in the chosen area!

******* 
ERROR! 
No viewpoints in the chosen area!

> 

> 

I don't understand this error, I've even manually added the point. Why don't you detect it?

**Comment by zoran-cuckovic** [comment]
Hi,
 if it doesn't work even when you add a point manually, it must be a projection problem. Switch off automatic projections ( "no projection" in CRS management) and see what happens.  See also https://landscapearchaeology.org/2020/wgs/ .

**Comment by Jhonnylerony** [comment]
Thank you, you were absolutely right, the cape had not turned well. I very much appreciate the comment, I know it is a common problem but it helped me focus on the solution.
