### ISSUE TITLE
Binary viewshed: Invalid and variable results (All 0 Values, no 1 values)

### ISSUE THREAD

**Issue by archaeolithics85** [zoran-cuckovic/QGIS-visibility-analysis#45]
I am trying to generate viewsheds for a set of archaeolocigal sites in the Levant. However results are varying depending on the raster resolution (25 m & 100 m) and the raster type (float32 and int16)

The original raster data is the aster 3 dataset from the NASA Geoviewer.

Observer height was set to 1.7 m and target height of 1.1 at a max distance of 1400m. I tried to process the binary viewshed. The dataset contains 52 locations which I have tried to iterate through them, but in several cases the result is a circle of 0-values even though there should be visbility > 0. However, when I change the raster-resolution or the data-type, results may vary, but generally are wrong, still. 

I hope you can help me. And general thanks for providing this fine software.

![image](https://user-images.githubusercontent.com/69504499/89879530-64889600-dbc3-11ea-8aba-2a73a479f1fe.png)

![image](https://user-images.githubusercontent.com/69504499/89879559-6eaa9480-dbc3-11ea-9701-4070618a943e.png)

**Comment by zoran-cuckovic** [comment]
Hello,
An all zero raster is not a valid result - at least the centre pixel(s) should be marked as visible. Perhaps you have a projection issue: it seems that your points don't sit inside the perimeter of the viewshed ? Switch off the automatic re-projection in QGIS ("no projection") and see what happens. For visibility modelling, 100 metres raster is probably too coarse (unless you analyse very large areas).

**Comment by archaeolithics85** [comment]
Thanks for the swift answer. No, all rasters are in the same CRC, the issue prevails both with projection on and off. Points are located correctly (In the images shown above, the viewshed-layer is placed above the point layer). I tested both the original aster3 raster and the resampled 100 m raster, both generate the same issue.

Until now I was able to narrow the issue down to the merging process of the aster3 tiles to a larger raster dataset. When the raster is merged (Keeping all properties the same) the issue happens. When I use the single tiles and just reproject them from WGS84 to EPSG 23036 the problems appear. I also have tried merging via GDAL, GRASS and SAGA which all resulted in the same issue.

As you have written, visibility should at least be positive for the central cell. But it isn't... unfortunately.

![image](https://user-images.githubusercontent.com/69504499/90015113-6bd59f80-dca8-11ea-94ea-56fab23e41be.png)

**Comment by archaeolithics85** [comment]
I am still trying to solve this issue. I have now narrowed down the issue to this case:

Datasets in use
DEM based on ASTER3 Dataset (30 m reprojected to EPSG 32636)
Point Dataset with archaeological sites (EPSG 32636)

When a selection of points from the Point dataset is processed without iteration it seems to work:

![image](https://user-images.githubusercontent.com/69504499/90393693-8ab1a880-e091-11ea-9428-f133994895ed.png)

When the same selection is iterated (All other properties remain the same) it does not work:

![image](https://user-images.githubusercontent.com/69504499/90393742-a3ba5980-e091-11ea-94f4-f005d5b1fe21.png)

When single point from Dataset is selected and processed without iteration it does not work:

![image](https://user-images.githubusercontent.com/69504499/90393815-c3ea1880-e091-11ea-990b-1f28d52abe1a.png)

The plugin seems to be massively erratic in this case. I also have tested other projection systems and QGIS 3.4 as well as 3.10.

**Comment by archaeolithics85** [comment]
So, ok. The issue _only_ appears when features are iterated or selected manually. I also checked completely other datasets. This thing here does not work properly...

**Comment by zoran-cuckovic** [comment]
I'm closing this potential issue, as so far it hasn't been raised again. There can be many reasons for such bizzare behaviour, it remains unclear...
