### ISSUE TITLE
Feature Request: Observer Point VFOV masking

### ISSUE THREAD

**Issue by cannibalflea** [zoran-cuckovic/QGIS-visibility-analysis#46]
I was wondering if there are any plans for adding vertical angle masking to the plugin. 

Based on your [recent blog post](https://landscapearchaeology.org/2020/direction-viewshed/), it seems there is now the possibility to control the inner radius in additional to the global variable controlling outer radius as well as the horizontal field of view using the azimuth attributes for the observer points. I was hoping you would be able to add the vertical field of view as well so that would cover all the constraints (see ArcMap [observer tool definition](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/using-viewshed-and-observer-points-for-visibility.htm#ESRI_SECTION1_E858A064D6AB4B7F9E95316D72627ED9)). 

My main interest is using this tool to calculate the approximate area in the view of a drone based on the drone altitude and pitch and yaw of the camera. I am hoping to be able to generate some bounding boxes around each drone image's visible range to make it easier to choose the right image for the area of interest.

Thanks again for such an excellent tool 👍

**Comment by zoran-cuckovic** [comment]
Hello, 
Yes, that's one of _many_ things that are missing... I don't have a plan at the moment (I'm quite busy) but in the (unspecified) future, I do plan to introduce this feature.

**Comment by zoran-cuckovic** [comment]
Implemented in v. 1.3
