### ISSUE TITLE
Negative values for observer height

### ISSUE THREAD

**Issue by GustyLa** [zoran-cuckovic/QGIS-visibility-analysis#48]
Would it be possible to make the observer height accept negative values? I would like to know how visible an existing mound would be if it were 5m lower, but entering negative values only returns an all 0 values raster.

**Comment by zoran-cuckovic** [comment]
Hello, 
An underground viewshed cannot be implemented... You'll need to edit your DEM, in order to remove the mounds. See https://gis.stackexchange.com/questions/40873/modifying-single-pixel-values-in-qgis

**Comment by GustyLa** [comment]
Hello. Thanks for the tip - and keep up the good work! The extension is great!
