### ISSUE TITLE
Create Viewpoints does not create target_hgt field

### ISSUE THREAD

**Issue by PedroVenancio** [zoran-cuckovic/QGIS-visibility-analysis#50]
Hi @zoran-cuckovic 

I see that when I run the Create Viewpoints with the **Field value for observer height** option, it does not create target_hgt field in the output layer. I believe it considers it as 0 and so it ignores it.

If I use the numeric **Target height, meters** option, it already creates the target_hgt field, with the unique target height.

Can you replicate?

I'm testing it in QGIS 3.16.2, on Windows.

**Comment by zoran-cuckovic** [comment]
Yes, I can replicate the problem - I will fix the issue in the following days.
Thanks for reporting the bug !

**Comment by zoran-cuckovic** [comment]
Fixed in 1.4 version.
