### ISSUE TITLE
ModuleNotFoundError: No module named 'gdal'

### ISSUE THREAD

**Issue by PedroVenancio** [zoran-cuckovic/QGIS-visibility-analysis#51]
Hi @zoran-cuckovic 

`import gdal` is deprecated and removed from GDAL 3.2.1 version that will be used in the next release cicle, as you can see in https://pypi.org/project/GDAL/ section "Usage"

You need to update the code to https://github.com/qgis/QGIS-Mac-Packager/issues/114#issuecomment-778976859

**Comment by zoran-cuckovic** [comment]
Ok, thanks for signalling the issue. It's on the list of fixes for the next version.

**Comment by zoran-cuckovic** [comment]
Fixed in 1.5 version.

**Comment by PedroVenancio** [comment]
Thank you very much @zoran-cuckovic !
