### ISSUE TITLE
Unable to load the plugin

### ISSUE THREAD

**Issue by CommunyAS** [zoran-cuckovic/QGIS-visibility-analysis#55]
I installed the plugin both using the QGIS plugin manager and from ZIP, but loading the plugin does not work resulting in the following message (for details see screen shot and QGIS log):

**_Couldn't load plugin 'ViewshedAnalysis' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'plugins.processing'_** 

I checked, all the paths in the log message are set correctly.
I run the latest QGISl-LTR (3.16.8) on macOS 10.13.6 (High Sierra)

![Screen Shot 2021-07-30 at 13 15 08 (CEST)](https://user-images.githubusercontent.com/74900017/127645217-629b25fc-72a9-41f0-931a-67dccfdad81c.png)

_[QGIS Error Log.txt](https://github.com/zoran-cuckovic/QGIS-visibility-analysis/files/6907143/QGIS.Error.Log.txt)_

**Comment by zoran-cuckovic** [comment]
Hello! 
You seem to have a problem with qgis Processing - do you have problems with other Processing plugins ( other than built- ones) ?

**Comment by CommunyAS** [comment]
I realised that also GRASS doesn’t work now, but did not have time yet to check if other processing are affected too
