### ISSUE TITLE
Problem running the algorithms from qgis_process

### ISSUE THREAD

**Issue by JanCaha** [zoran-cuckovic/QGIS-visibility-analysis#59]
Since QGIS 3.16 there is a possibility to run tools (algorithms) from command line using tool **qgis_process** without having to actually open QGIS. This allows running QGIS tools from other languages ie. R - [package qgisprocess](https://github.com/paleolimbot/qgisprocess). The tools runned from **qgis_process** are handled somewhat differently (not exactly sure how, but there is a difference).

The way how the plugin is currently loaded ([here](https://github.com/zoran-cuckovic/QGIS-visibility-analysis/blob/af9c51759a7b408050d58e6f06bb5c3363843e10/visibility_provider.py#L52)) causes that **qgis_process** does not see the plugin at all and thus the tools are not available outside of QGIS. The problem is probably with setting the settings values and then only adding tools if the setting **VISIBILITY_ANALYSIS_ACTIVATED** is **True** [(it is done here)](https://github.com/zoran-cuckovic/QGIS-visibility-analysis/blob/af9c51759a7b408050d58e6f06bb5c3363843e10/visibility_provider.py#L82).

Maybe this could be handled differently? For example add the settings in main plugin init (instead of provider) and then checked if the setting exist and if does not, use some sensible default value? I would be happy to do prepare pull request to solve this issue.

**Comment by zoran-cuckovic** [comment]
Thank you Jan, 
It's true that the ACTIVATED setting is not really needed - we can des/activate the plugin under Plugins menu. However, most of Processing plugins do include this option, which is accessed in Processing settings. If you have a solution for this, please do make a pull request, I'll integrate it to the main code.

**Comment by JanCaha** [comment]
After some testing it seems that settings are not the problem. The issues are just minor changes. The solution is in #60.

I noticed one other minor thing that could be improved. The `name()` function for algorithm should return the name in the form of identificator. The standard is to use lower case without space or underscore (you can see it in QGIS algorithms). This is the identificator QGIS uses, along with plugin name, to actually run the algorim.  It might be convenient to change the names. The displayName() function can stay as they are, as this is used only in UI.

Currently the names are:
```
Intervisibility
Viewshed
create_viewpoints
visibility_index
```
So maybe it could be change to:
```
intervisibility
viewshed
createviewpoints
visibilityindex
```

**Comment by zoran-cuckovic** [comment]
Thanks, I've changed the names as you suggest.

**Comment by JanCaha** [comment]
Perfect. That should make the plugin much more user friendly, if it is used without the GUI.
