### ISSUE TITLE
Viewshed interference in triangle pattern

### ISSUE THREAD

**Issue by ikijohn** [zoran-cuckovic/QGIS-visibility-analysis#6]
I have struggled with a problem when using QGIS Viewshed. The problem is that a triangle interference pattern is created suggesting no visibility in areas that should be visible. This is particularly noticable after processing the DTM data and adding height information for buildings and trees. The triangle interference pattern occurs in other areas not affected by the tree or building height and seems not to relate to line of sight. I have tried everything I can think off, removing NULL values, reprojecting the rasta data, all without success. I am using OS Terrain 50 for the dtm. The triangles seem to connect to this grid. I thought that it might be something to do with the coarseness of the grid, but I have been able to use the 50m DTM in the past without issues of this problem. Do You have any ideas what could be causing this?? I have inspected the DTM and see no holes or anomalies relating to the triangles. 
Many thanks John

![visibility triangles 01](https://cloud.githubusercontent.com/assets/25506739/22552140/8e9484aa-e94f-11e6-954a-dfc8284c9a34.jpg)
![visibility triangles 02](https://cloud.githubusercontent.com/assets/25506739/22552141/8e94d946-e94f-11e6-8ff4-3f5978a83595.jpg)
![visibility triangles overview 03](https://cloud.githubusercontent.com/assets/25506739/22552139/8e8f3040-e94f-11e6-9a51-956bc81188dc.jpg)

**Comment by zoran-cuckovic** [comment]
Hello, 
At first sight it seems to me that you did not interpolate ("smoothen") your DEM. Your new resolution is - I guess - a couple of meters, while the data used is still in big, flat 50 meters blocks. Does that make sense ?

**Comment by ikijohn** [comment]
Hello Zoran.

 

Thank you for your reply. That indeed solved my problem.

 

I resampled and interpolated at a 10m grid and the triangles are gone.

 

What confused me originally is that on the 50m DTM with no added trees and buildings, I get no triangles but on a coarse grid. Then when I add trees and buildings I get random triangles, even though they are not in line of sight. 

 

But problem solved.

 

Thanks again.

 

John
