### ISSUE TITLE
Empty Try Catch Blocks

### ISSUE THREAD

**Issue by grl-sage** [zoran-cuckovic/QGIS-visibility-analysis#61]
Any reason you perform a "pass" on many of the try/catch blocks?  Fortify Scans do not like those and IT is making us modify the code so we get a clean scan.  The reasoning is that the code ignores an exception, which could cause the program
to overlook unexpected states and conditions.

Any future updates in the works for the plugin where these may be populated by at least appending to the "error" logging variable like in other parts of the code so we don't have to maintain code just to keep the try/catch blocks from being flagged as an issue?

**Comment by zoran-cuckovic** [comment]
Let me get this straight : you work in the commercial sector and you'd like me to adjust the code for your needs ?  You can DM me a proposal if you wish. Also, could you please provide the link to the repository, as stipulated by the GPL licence.
