### ISSUE TITLE
Creating a viewshed polygon for each viewpoint

### ISSUE THREAD

**Issue by RobShaw77** [zoran-cuckovic/QGIS-visibility-analysis#64]
I'm trying to do some analysis that captures both _where_ someone can see to but also _what_ they can see. E.g. I can't see very far because my view is blocked by green trees vs concrete building. I was hoping to do this by creating a viewshed polygons for each viewpoint and then intersecting that polyon with a separate land use layer. However, I can't see to find a way to get a polygon output from the tool, other by creating a huge number of target points and using the intervisibility network and creating a bounding envelope.

Could you tell me if what I'm trying to do is possible please?

Thanks
Rob

**Comment by zoran-cuckovic** [comment]
Hello, 
You can always convert a raster into a vector polygon (Raster -> vectorise [GDAL works perfectly] ). For a single point you can only have 0 and 1 for visibility, so it's just a single click of a button.
