### ISSUE TITLE
Use of GPU for computation

### ISSUE THREAD

**Issue by SchmidL** [zoran-cuckovic/QGIS-visibility-analysis#66]
Hi, 

I really love your plugin: simple to use but so powerful! My question was if there was an easy way to implement GPU computation (if wanted or the GPU is powerful enough). I stumbled over Numba https://numba.pydata.org/ to easily convert scripts to GPU computations, also numpy-based one. Or do you see any limitations?

Thx

**Comment by zoran-cuckovic** [comment]
Yes, that's a great idea, but it's also quite technical to code. I prefer Python/Numpy for the ease of maintenance and for further developement. I'm open for collaboration if someone would have a clean solution.
