### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by bellanz80** [zoran-cuckovic/QGIS-visibility-analysis#67]
Hi.
I have windows 10, and QGI's OSGEO installer.
I couldn't install ewl plugin since version 3.24, 3.26
It only works on 3.22.
The error is always the same
Thank you very much for your help!

![image](https://user-images.githubusercontent.com/38449926/197852359-3572c6ba-b1d7-4db8-9fa9-f47bf9f4a578.png)

**Comment by zoran-cuckovic** [comment]
This ain't my plugin, at all.
