### ISSUE TITLE
Stand alone python script

### ISSUE THREAD

**Issue by barnabasharris** [zoran-cuckovic/QGIS-visibility-analysis#68]
Hi, 
I'd like to use this function to process a very large area (total 90,000,000 points) using an HPC lustre system. Unless the software is centrally installed on the HPC (QGIS isn't) we have to compile the software ourselves. Ideally then, I would adapt the Viewshed python scripts from your module so that they can be run outside of QGIS, but am relatively unfamiliar with spatial python (I work in R). Before I embark on the journey, what are your thoughts on this, would it be possible to modify the scripts so that they accept a simple list of coords etc.?

All the best,

**Comment by zoran-cuckovic** [comment]
The plugin runs on QGIS libraries - which is a choice I made from the outset. Quite a number of folks from the commercial sector would like to have a standalone library, with zero investement. That being said, it's relatively straightforward to repalce QGIS calls with, for instance, GDAL routines, provided that you have some experience in Python.
