### ISSUE TITLE
Issue with radius_in, azim_1, azim_2

### ISSUE THREAD

**Issue by Kunicboll** [zoran-cuckovic/QGIS-visibility-analysis#71]
I am using the tool: Intervisibility Network

I have generated viewports from "create viewports" and i have those datatypes:
![image](https://user-images.githubusercontent.com/19748309/214780057-cd12b517-a326-49ba-8bd7-86240d49749c.png)

I have those values in my attributes:
![image](https://user-images.githubusercontent.com/19748309/214780791-b3492426-a769-49f3-bb67-1fdf1a0b5aa6.png)

The result i get is this:
![image](https://user-images.githubusercontent.com/19748309/214780128-f1c82d50-467c-4542-8a88-71d229c9fa4b.png)

Result is not using radius_in, azim_1, azim_2

**Comment by zoran-cuckovic** [comment]
Hello ! 
Yes, these parameters apply to the raster routine. For intervisibility lines you can filter out the unwanted data using the length of the line (radius_in) and the azimuth (in the field calculator). I agree that this is a bit fussy (azimuth at least)...
