### ISSUE TITLE
DeprecationWarning: QgsSpatialIndex.insertFeature()

### ISSUE THREAD

**Issue by andregracioso** [zoran-cuckovic/QGIS-visibility-analysis#74]
The viewshed tool is returning:

_"DeprecationWarning: QgsSpatialIndex.insertFeature() is deprecated"_. Is this something that need to be fixed?

**Comment by zoran-cuckovic** [comment]
Well, yes, the code should be updated, but the  QgsSpatialIndex.insertFeature() routine should continue to behave as expected.

**Comment by zoran-cuckovic** [comment]
Fixed in 1.9 version (pending approval)
