### ISSUE TITLE
Radius of analisis

### ISSUE THREAD

**Issue by Risi5mora** [zoran-cuckovic/QGIS-visibility-analysis#75]
Is it possible to insert a polygonal vector i.e. boundary shape file instead of the radius of analyses?

**Comment by zoran-cuckovic** [comment]
Hi, no it is not possible. You should use a mask : 
1) rasterize your polygon to dimensions of the viewshed raster. 
2) use the raster calculator to assign zero to undesired areas

**Comment by Risi5mora** [comment]
You could show me through a video, it's very difficult to understand through a written message
