### ISSUE TITLE
ClassFactory()

### ISSUE THREAD

**Issue by Skimkat** [zoran-cuckovic/QGIS-visibility-analysis#76]
Hi Zoran,
I used to use the Visibility plugin but now it doesn't want to load with the following error -
Couldn't load plugin 'ViewshedAnalysis' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'plugins.processing' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ViewshedAnalysis\__init__.py", line 37, in classFactory
    from .visibility_plugin import VisibilityPlugin
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ViewshedAnalysis\visibility_plugin.py", line 37, in 
    from .visibility_provider import VisibilityProvider
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ViewshedAnalysis\visibility_provider.py", line 40, in 
    from .algorithms.viewshed_raster import ViewshedRaster
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ViewshedAnalysis\algorithms\viewshed_raster.py", line 26, in 
    from plugins.processing.gui import MessageBarProgress
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'plugins.processing'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.2-Zanzibar Zanzibar, 4470baa1a3 
Python Path:
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometric_attributes
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deg_2_dms
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AreaAlongVector
•	C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
•	C:\Program Files\QGIS 3.8\bin\python37.zip
•	C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
•	C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
•	C:\Program Files\QGIS 3.8\bin
•	C:\PROGRA~1\QGIS3~1.8\apps\Python37
•	C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
•	C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
•	C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:\Users\Sarien\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
•	C:\Users\Sarien\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geosys-plugin
•	C:\Users\Sarien\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
•	C:\Users\Sarien\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
•	C:/Users/Sarien/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
•	C:\Users\Sarien\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\Sarien\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
 Will appreciate any assistance. Thank you

**Comment by zoran-cuckovic** [comment]
Hello, 
This is a strange issue that was normally fixed some time ago. I can see that you have an old QGIS version : upgrade to 3.30+ and **reinstall** the plugin to be sure.

**Comment by Romain082** [comment]
Hello Zoran,
Have been experiencing the same issue for some weeks now, and upgrading QGIS to 3.30+ sadly didn't do the trick
Thank you for your time and your amazing plugin

**Comment by zoran-cuckovic** [comment]
OK - I'll take this into account for the new update.

**Comment by TravellingTortoise** [comment]
Yes been trying it in different versions 3.4, 3.8, 3.3  - problem still persists.

**Comment by andre-kotze** [comment]
Same problem in 3.34. I changed line 26 in `viewshed_raster.py` and line 11 in `viewshed_index.py` from `from plugins.processing.gui import MessageBarProgress` to `from processing.gui import MessageBarProgress` and reloaded the plugin. Now it works after only these two changes... Great Plugin thanks

**Comment by zoran-cuckovic** [comment]
Thanks a lot for this solution! I hope to find some time soon for an update of the plugin...

**Comment by zoran-cuckovic** [comment]
Fixed in 1.9 version (pending approval)
