### ISSUE TITLE
Error in QGIS 3.36 RC 

### ISSUE THREAD

**Issue by pigreco** [zoran-cuckovic/QGIS-visibility-analysis#77]
![image](https://github.com/zoran-cuckovic/QGIS-visibility-analysis/assets/7631137/5acefb9f-c3e2-41d5-b5b9-d789e66a5b87)

## OSGeo4W network installer Win 11 64b

Versione di QGIS
3.36.0-Maidenhead
Revisione codice QGIS
09951dc0
Versione Qt
5.15.3
Versione Python
3.9.18
Versione GDAL/OGR
3.8.4
Versione PROJ
9.3.1
Versione database del Registro EPSG
v10.098 (2023-11-24)
Versione GEOS
3.12.1-CAPI-1.18.1
Versione SQLite
3.41.1
Versione PDAL
2.6.0
Versione client PostgreSQL
16.1
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
DataPlotly
4.1.0
felt
2.0.0
GroupStats
2.2.7
kmltools
3.1.32
Label On Off
0.1
layer2kmz
1.5.3
nominatim_locator_filter
0.3.2
OpenAndFilterAttributeTable
0.1
osminfo
0.8.1
processing_r
4.1.0
profiletool
4.2.6
qchainage
3.0.1
qconsolidate
1.1.0
qgis-raster-attribute-table-plugin-bugfix-gh16
1.0
Qgis2threejs
2.7.3
QuickOSM
2.2.3
quick_map_services
0.19.34
redLayer
2.2
SelectionFilter
1.0
SLD4raster
1.0
soar
1.0.2
StyleLoadSave
1.0
valuetool
3.0.17
ViewshedAnalysis
1.8
wbt_for_qgis
1.0.9
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
latlontools
3.6.19

**Comment by florianneukirchen** [comment]
Fixed in pull request #78

**Comment by zoran-cuckovic** [comment]
Fixed in 1.9 version (pending approval)
