### ISSUE TITLE
Field value for observer height not working in Graphical Modeler

### ISSUE THREAD

**Issue by Paul-A-Kavan** [zoran-cuckovic/QGIS-visibility-analysis#81]
Hello, Zoran thank you for this fantastic plugin!
I'm having an issue using the viewpoint function in the graphical modeler. Admittedly, I'm new to QGIS so I am unable to judge confidently whether I'm making a mistake or if there really is an issue with the code. My apologies if this is a user error on my part. 

When I run viewpoints manually I am able to select an attribute column ("height") for the "Field value for observer height" argument, which is then turned into the "observ_hgt" column in the viewpoints result. This allows me to supply unique heights for each input point. Doing this works perfectly!

But when I attempt to create the same viewpoints using the graphical modeler, the viewpoints algorithm won't use the attribute column for the observer height. It either errs or ignores the provided attribute name depending on how you attempt to provide the attribute.
Below are a couple images to indicate the basics of my approach. 

Thank you. 

![image](https://github.com/user-attachments/assets/1dfb2567-75b2-4752-82a2-c237ecf52b0a)

![image](https://github.com/user-attachments/assets/2acab0de-efc6-4c28-8373-29f1bf0215ad)

**Comment by zoran-cuckovic** [comment]
Hello, 
the field value parameter is set to a 'calculated field' , considering your screenshot. It should be fed by a table field value. Does it work in that configuration?

**Comment by Paul-A-Kavan** [comment]
Thank you for the response, you are correct. Everything works fine and it was my mistake. Thanks for this awesome plugin!

For anyone making this beginner mistake in the future: I thought that the "123" in the "Value" input icon implied only numeric inputs so then I switched to "Pre-Calculated Value" and tried every which way to get or name the field from the attribute table. It is so much simpler than all that... You just provide the unquoted attribute name to the field value input with type "Value".
