### ISSUE TITLE
Problem with MultiPoint layers

### ISSUE THREAD

**Issue by PedroVenancio** [zoran-cuckovic/QGIS-visibility-analysis#9]
Hi,

It seems that Viewshed Analysis does not work well with multipoint layers. 

In both cases, it runs, but the result for multipoint layers is always centred in the coordinates [0,0] of the reference system.

You can get two sample shapefiles (one point and another multipoint) from here: https://cld.pt/dl/download/663aaf77-d786-43f2-967d-515c2a9fe676/sample_point_multipoint.zip 

They are in EPSG:3763 CRS.

You can also get a sample DEM in EPSG:3763, from here: https://cld.pt/dl/download/baf86f62-c8ab-4e56-b557-ba4dce8a9b7d/dem_srtm_pttm06_80m.tif.bz2 

Tested in both windows and linux, with Viewshed Analysis 0.5.4 and some prior versions.

Thank you very much for your work Zoran!

**Comment by zoran-cuckovic** [comment]
Hello,

No, it does not work with multi-points: you should convert your data to standard point layer. I will see what can be done about that...

Regards

**Comment by PedroVenancio** [comment]
Hi Zoran,

Thanks for the reply! Maybe you can add that info in the Reference tab of the plugin, in 'Data - Observer points' and in http://zoran-cuckovic.from.hr/QGIS-visibility-analysis/#1.

Thank you very much! Best regards,
Pedro
